/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin.dashboard'
import { Route as SuperadminCommitteesRouteImport } from './routes/superadmin.committees'
import { Route as SuperadminApprovalsRouteImport } from './routes/superadmin.approvals'
import { Route as SuperadminAdminsRouteImport } from './routes/superadmin.admins'
import { Route as StudentRegistrationsRouteImport } from './routes/student.registrations'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentEventsRouteImport } from './routes/student.events'
import { Route as AdminVolunteersRouteImport } from './routes/admin.volunteers'
import { Route as AdminScannerRouteImport } from './routes/admin.scanner'
import { Route as AdminLogisticsRouteImport } from './routes/admin.logistics'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as StudentEventsEventIdRouteImport } from './routes/student.events_.$eventId'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminCommitteesRoute = SuperadminCommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminApprovalsRoute = SuperadminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAdminsRoute = SuperadminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => SuperadminRoute,
} as any)
const StudentRegistrationsRoute = StudentRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentEventsRoute = StudentEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => StudentRoute,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScannerRoute = AdminScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogisticsRoute = AdminLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const StudentEventsEventIdRoute = StudentEventsEventIdRouteImport.update({
  id: '/events_/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/student/events': typeof StudentEventsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/registrations': typeof StudentRegistrationsRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/approvals': typeof SuperadminApprovalsRoute
  '/superadmin/committees': typeof SuperadminCommitteesRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/student/events/$eventId': typeof StudentEventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/student/events': typeof StudentEventsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/registrations': typeof StudentRegistrationsRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/approvals': typeof SuperadminApprovalsRoute
  '/superadmin/committees': typeof SuperadminCommitteesRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/student/events/$eventId': typeof StudentEventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/student/events': typeof StudentEventsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/registrations': typeof StudentRegistrationsRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/approvals': typeof SuperadminApprovalsRoute
  '/superadmin/committees': typeof SuperadminCommitteesRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/student/events_/$eventId': typeof StudentEventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/superadmin'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/logistics'
    | '/admin/scanner'
    | '/admin/volunteers'
    | '/student/events'
    | '/student/profile'
    | '/student/registrations'
    | '/superadmin/admins'
    | '/superadmin/approvals'
    | '/superadmin/committees'
    | '/superadmin/dashboard'
    | '/admin/'
    | '/student/'
    | '/superadmin/'
    | '/student/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/logistics'
    | '/admin/scanner'
    | '/admin/volunteers'
    | '/student/events'
    | '/student/profile'
    | '/student/registrations'
    | '/superadmin/admins'
    | '/superadmin/approvals'
    | '/superadmin/committees'
    | '/superadmin/dashboard'
    | '/admin'
    | '/student'
    | '/superadmin'
    | '/student/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/superadmin'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/logistics'
    | '/admin/scanner'
    | '/admin/volunteers'
    | '/student/events'
    | '/student/profile'
    | '/student/registrations'
    | '/superadmin/admins'
    | '/superadmin/approvals'
    | '/superadmin/committees'
    | '/superadmin/dashboard'
    | '/admin/'
    | '/student/'
    | '/superadmin/'
    | '/student/events_/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  SuperadminRoute: typeof SuperadminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/committees': {
      id: '/superadmin/committees'
      path: '/committees'
      fullPath: '/superadmin/committees'
      preLoaderRoute: typeof SuperadminCommitteesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/approvals': {
      id: '/superadmin/approvals'
      path: '/approvals'
      fullPath: '/superadmin/approvals'
      preLoaderRoute: typeof SuperadminApprovalsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/admins': {
      id: '/superadmin/admins'
      path: '/admins'
      fullPath: '/superadmin/admins'
      preLoaderRoute: typeof SuperadminAdminsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/student/registrations': {
      id: '/student/registrations'
      path: '/registrations'
      fullPath: '/student/registrations'
      preLoaderRoute: typeof StudentRegistrationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/events': {
      id: '/student/events'
      path: '/events'
      fullPath: '/student/events'
      preLoaderRoute: typeof StudentEventsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scanner': {
      id: '/admin/scanner'
      path: '/scanner'
      fullPath: '/admin/scanner'
      preLoaderRoute: typeof AdminScannerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logistics': {
      id: '/admin/logistics'
      path: '/logistics'
      fullPath: '/admin/logistics'
      preLoaderRoute: typeof AdminLogisticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/events_/$eventId': {
      id: '/student/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/student/events/$eventId'
      preLoaderRoute: typeof StudentEventsEventIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminLogisticsRoute: typeof AdminLogisticsRoute
  AdminScannerRoute: typeof AdminScannerRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminLogisticsRoute: AdminLogisticsRoute,
  AdminScannerRoute: AdminScannerRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentEventsRoute: typeof StudentEventsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentRegistrationsRoute: typeof StudentRegistrationsRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentEventsEventIdRoute: typeof StudentEventsEventIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentEventsRoute: StudentEventsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentRegistrationsRoute: StudentRegistrationsRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentEventsEventIdRoute: StudentEventsEventIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface SuperadminRouteChildren {
  SuperadminAdminsRoute: typeof SuperadminAdminsRoute
  SuperadminApprovalsRoute: typeof SuperadminApprovalsRoute
  SuperadminCommitteesRoute: typeof SuperadminCommitteesRoute
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminAdminsRoute: SuperadminAdminsRoute,
  SuperadminApprovalsRoute: SuperadminApprovalsRoute,
  SuperadminCommitteesRoute: SuperadminCommitteesRoute,
  SuperadminDashboardRoute: SuperadminDashboardRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  SuperadminRoute: SuperadminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
